---
title: "CamCat Exp"
author: "Marco Willi"
date: "13 Oktober 2017"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE}

# fig.height=width_large, fig.width=width_large
width_large <- 12
height_large <- 12
height_very_large <- 18

# fig.height=width_med, fig.width=width_med
width_med <- 10
height_med <- 10

# fig.height=width_small, fig.width=width_small
width_small <- 6
height_small <- 6

width_variable <- width_small + min(1/width_small, width_small)
height_varialbe <- height_small + min(1/height_small, width_small)


############################ -
# Libraries ----
############################ -

library(dplyr)
library(ggplot2)
library(reshape2)
library(jpeg)
library(grid)
library(gridExtra)

############################ -
# Parameters Fix ----
############################ -

path_main <- "D:/Studium_GD/Zooniverse/Data/transfer_learning_project/"
path_project <- "db/camcat2/"
fname <- "classifications_experiment_20171008_converted.csv"
path_scratch <- "D:/Studium_GD/Zooniverse/Data/transfer_learning_project/scratch/camcat2/"

############################ -
# Read Classifications ----
############################ -

data_raw <- read.csv2(paste(path_main, path_project, fname, sep=""),sep = ",", quote = "\"", header = TRUE)


############################ -
# Group to subject ----
############################ -


names(data_raw)[names(data_raw)=="workflow"] = "workflow_current"
data <- dcast(data = filter(data_raw, !attr %in% c("subject_id")), formula = subject_id + workflow_current ~ attr, value ="value")
names(data) <- sapply(names(data), function(x){gsub(pattern = "#","", x)})
data$machine_probability <- as.numeric(data$machine_probability)

data$workflow_current <- factor(data$workflow_current, levels=c("5000", "5001", "4963"))

# group totals
group_totals <- group_by(data, experiment_group) %>% summarise(n_in_group=n_distinct(subject_id))
group_totals

data <- left_join(data, group_totals, by="experiment_group")

data$machine_prediction_workflow <- ifelse(data$workflow_current == '5000',
                                         ifelse(data$machine_prediction == "blank", "blank", "notblank"),
                                         ifelse(data$workflow_current == '5001', 
                                                ifelse(data$machine_prediction == "vehicle", "vehicle", "novehicle"),data$machine_prediction))
data$x_pred_agreement <- ifelse(tolower(data$machine_prediction_workflow) == tolower(data$plur_label),1,0)

```


# Visualize


```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}               
data_gg <- group_by(data, workflow_current, experiment_group, retirement_reason) %>% summarise(n=n()/max(n_in_group))
ggplot(data_gg, aes(x=workflow_current,y=n)) + geom_bar(stat="identity") + facet_grid(experiment_group~retirement_reason)


data_gg <- group_by(data, workflow_current, experiment_group) %>% summarise(n=n()/max(n_in_group))
ggplot(data_gg, aes(x=workflow_current,y=n)) + geom_bar(stat="identity") + facet_wrap("experiment_group")

data_gg <- group_by(data, workflow_current, experiment_group) %>% summarise(n=n()/max(n_in_group))
ggplot(data_gg, aes(x=workflow_current,y=n)) + geom_bar(stat="identity") + facet_wrap("experiment_group")


# overlap
data_gg <- group_by(data, workflow_current, experiment_group, retirement_reason, n_users) %>% summarise(n=n()/max(n_in_group))
ggplot(data_gg, aes(x=workflow_current,y=n)) + geom_bar(stat="identity") + facet_grid(experiment_group~retirement_reason+n_users)
```


```{r}
############################ -
# Inspect ----
############################ -

insp <- filter(data, workflow_current == "5000" & retirement_reason == "consensus" & n_users == 2 & experiment_group==1)
head(insp)


############################ -
# Check machine prediction
# and retirement ----
############################ -
```


```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# all current estimates
tt2 = group_by(data, workflow_current, machine_prediction_workflow, plur_label) %>% summarise(n=n())
n_total <- group_by(tt2, workflow_current) %>% summarise(n_workflow=sum(n))
tt3 <- left_join(tt2,n_total) %>% mutate(p_total=n/n_workflow)

ggplot(tt3, aes(x=machine_prediction_workflow,y=plur_label)) + 
  geom_tile(aes(fill = p_total), colour = "white") + 
  geom_text(aes(label = round(p_total, 3))) +
  scale_fill_gradient(low = "white",high = "steelblue") +
  facet_wrap("workflow_current", scales = "free")

```

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# only retired subjects
tt2 = filter(data,  !is.na(ret_retired_at) & !(plur_label == "unknown answer label")) %>% group_by(workflow_current, machine_prediction_workflow, plur_label) %>% summarise(n=n())
n_total <- group_by(tt2, workflow_current) %>% summarise(n_workflow=sum(n))
tt3 <- left_join(tt2,n_total) %>% mutate(p_total=n/n_workflow)

ggplot(tt3, aes(x=machine_prediction_workflow,y=plur_label)) + 
  geom_tile(aes(fill = p_total), colour = "white") + 
  geom_text(aes(label = round(p_total, 3))) +
  scale_fill_gradient(low = "white",high = "steelblue") +
  facet_wrap("workflow_current", scales = "free")



# look at wrong predictions
wrong_p <- filter(data, (tolower(machine_prediction_workflow) != tolower(plur_label)) & !is.na(ret_retired_at))
wrong_p[1:30,]
```

# Check machine disagreement samples ----


```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
wrongs <- filter(data, (x_pred_agreement==0) & (experiment_group==1))

set.seed(456)
sample_wrongs <- wrongs[sample(1:dim(wrongs)[1],size = 6, replace = FALSE),]

urls <- sample_wrongs$link
preds <- sample_wrongs$machine_prediction_workflow
trues <- sample_wrongs$plur_label
probs <- sample_wrongs$machine_probability
subject_ids <- sample_wrongs$subject_id

# list of all figures
grobs <- list()
ncol=2
nrow=3
for (ii in 1:length(urls)){
  id <- subject_ids[ii]
  pred <- preds[ii]
  true <- trues[ii]
  prob <- probs[ii]
  url <- urls[ii]
  file_name <- paste(path_scratch,"image_",ii,".jpeg",sep="")
  download.file(url, destfile = file_name, mode = 'wb')
  
  img <- readJPEG(file_name)
  
  
  gg1 <- ggplot(data.frame(x=0:1,y= 0:1),aes(x=x,y=y), geom="blank") +
    annotation_custom(rasterGrob(img, width=unit(1,"npc"), height=unit(1,"npc")), 
                      -Inf, Inf, -Inf, Inf) + theme_minimal() +
    theme(axis.title = element_blank(), axis.text = element_blank()) +
    theme(plot.margin = unit(c(0.7,0.9,0,0.9), "cm"))
  
  pred <- data.frame(prob=prob, class=pred)
  
  gg2 <- ggplot(pred, aes(x=reorder(class, prob),y=prob)) + geom_bar(stat="identity") +
    coord_flip() +
    theme_light() +
    ylab("Model Output") +
    xlab("") +
    ggtitle("Model Prediction") +
    theme(axis.text.y=element_blank(), axis.text.x=element_text(size=16),
          axis.title.x=element_text(size=16),
          axis.title.y=element_text(size=16),
          plot.title = element_text(size=16),
          axis.ticks.y = element_blank()) +
    geom_text(aes(label=paste(class," (",round(prob,3)*100," %)",sep=""), y=0.05), size=4,fontface="bold", vjust="middle", hjust="left") +
    theme(plot.margin = unit(c(0.7,0.9,0.5,0.9), "cm"), panel.border=element_rect(fill=NA)) +
    scale_y_continuous(expand=c(0,0), limits = c(0,1)) +
    labs(x=NULL)
  title=textGrob(label = paste("True class: ",true,sep=""),gp=gpar(fontface="bold"), vjust=1)
  ga <- arrangeGrob(gg1,gg2,top=title)
  
  gb <- rectGrob(height = .98, width = .98, gp = gpar(lwd = 1.5, col = "blue",  fill=rgb(1, 1, 1, 0))) # border
  gt <- gTree(children = gList(ga, gb))
  
  grobs[[ii]] <- gt
}
ml <- marrangeGrob(grobs, nrow=nrow, ncol=ncol, top="")
ml
```




# Check machine agreement and score distr 

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}

# compare density distributions
text_large=10
text_med=8
text_small=6
ggplot(data, aes(x=machine_probability,fill=factor(x_pred_agreement))) + geom_density(alpha=0.3) +
  facet_wrap("workflow_current", scales="free") +
  ggtitle("Density of correctly/wrongly predicted classes") + 
  theme_light() +
  xlab("Model Output") +
  ylab("Density") + 
  scale_fill_brewer(type = "qual",direction = -1, palette=2) +
  theme(axis.text = element_text(size=text_large),
        axis.title = element_text(size=text_large),
        legend.text = element_text(size=text_med),
        legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_blank(),
        legend.background = element_rect(size=1,colour="black"),
        strip.text.x = element_text(size = text_small, colour = "white", face="bold")) +
  scale_y_sqrt()
```

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# compare density distributions by experiment group
text_large=10
text_med=8
text_small=6
ggplot(data, aes(x=machine_probability,fill=factor(x_pred_agreement))) + geom_density(alpha=0.3) +
  facet_grid(workflow_current~experiment_group, scales="free") +
  ggtitle("Density of correctly/wrongly predicted classes") + 
  theme_light() +
  xlab("Model Output") +
  ylab("Density") + 
  scale_fill_brewer(type = "qual",direction = -1, palette=2) +
  theme(axis.text = element_text(size=text_large),
        axis.title = element_text(size=text_large),
        legend.text = element_text(size=text_med),
        legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_blank(),
        legend.background = element_rect(size=1,colour="black"),
        strip.text.x = element_text(size = text_small, colour = "white", face="bold")) +
  scale_y_sqrt()
```

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# compare absolute values
ggplot(data, aes(x=machine_probability,fill=factor(x_pred_agreement))) + geom_histogram(position = "dodge", binwidth = 0.1) +
  facet_wrap("workflow_current", scales="free") +
  ggtitle("Density of correctly/wrongly predicted classes") + 
  theme_light() +
  xlab("Model Output") +
  ylab("# cases") + 
  scale_fill_brewer(type = "qual",direction = -1, palette=2) +
  theme(axis.text = element_text(size=text_large),
        axis.title = element_text(size=text_large),
        legend.text = element_text(size=text_med),
        legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_blank(),
        legend.background = element_rect(size=1,colour="black"),
        strip.text.x = element_text(size = text_small, colour = "white", face="bold"))
```

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# compare absolute values by experiment group
ggplot(data, aes(x=machine_probability,fill=factor(x_pred_agreement))) + geom_histogram(position = "dodge", binwidth = 0.05) +
  facet_grid(workflow_current~experiment_group, scales="free") +
  ggtitle("Density of correctly/wrongly predicted classes") + 
  theme_light() +
  xlab("Model Output") +
  ylab("# cases") + 
  scale_fill_brewer(type = "qual",direction = -1, palette=2) +
  theme(axis.text = element_text(size=text_large),
        axis.title = element_text(size=text_large),
        legend.text = element_text(size=text_med),
        legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_blank(),
        legend.background = element_rect(size=1,colour="black"),
        strip.text.x = element_text(size = text_small, colour = "white", face="bold"))
```


# Look at retirement over time

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# retirement per day
ggplot(filter(data,!is.na(ret_retired_at)), aes(x=as.Date(ret_retired_at),fill=experiment_group)) + 
  geom_bar(position="dodge") + 
  facet_wrap("workflow_current") +
  theme_light()
```

```{r, echo=FALSE, fig.height=height_large, fig.width=width_large}
# classifications per day
dat_gg <- filter(data, !is.na(ret_retired_at)) %>% 
  group_by(as.Date(ret_retired_at), workflow_current, experiment_group) %>%
  summarise(n_users=sum(as.numeric(n_users)), n_ret=n())
names(dat_gg) <- c("ret_retired_at", "workflow_current", "experiment_group", "n_users", "n_ret")
ggplot(dat_gg, aes(x=ret_retired_at,y=n_users/n_ret, colour=experiment_group)) + 
  geom_line(lwd=2)+ 
  facet_grid(workflow_current~.) +
  theme_light() +
  scale_y_continuous(limits=c(0,10))
```
